project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "ARIA Xenium Analysis"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Cell Types
        href: 20260302-cell_types.qmd
      - text: DE Analysis
        menu:
          - text: All cell types
            href: deg_analyses/20260304-DEG_allCellTypes_brainRegions.qmd
          - ---
          - text: Summary cell types x brain regions
            href: deg_analyses/20260306-DEG_summary_allCellTypes.qmd
          - ---
          - text: Microglia
            href: deg_analyses/20260303-DEG_MG_brainRegions.qmd
          - text: Astrocytes
            href: deg_analyses/20260303-DEG_astrocytes_brainRegions.qmd
          - text: Endothelial
            href: deg_analyses/20260303-DEG_ENDOTHELIAL_brainRegions.qmd
          - text: Oligodendrocytes
            href: deg_analyses/20260303-DEG_oligo_brainRegions.qmd
          - text: OPC
            href: deg_analyses/20260303-DEG_OPC_brainRegions.qmd
          - text: BAM
            href: deg_analyses/20260309-DEG_BAM_brainRegions.qmd
          - text: T-Cell
            href: deg_analyses/20260309-DEG_TCell_brainRegions.qmd
          - text: GABAergic Neuron 1
            href: deg_analyses/20260310-DEG_GABAergicNeuron1_brainRegions.qmd
          - text: GABAergic Neuron 2
            href: deg_analyses/20260310-DEG_GABAergicNeuron2_brainRegions.qmd
          - text: GABAergic Neuron 3
            href: deg_analyses/20260310-DEG_GABAergicNeuron3_brainRegions.qmd
          - text: GABAergic Neuron 4
            href: deg_analyses/20260310-DEG_GABAergicNeuron4_brainRegions.qmd
          - text: Glutamatergic Neuron 1
            href: deg_analyses/20260310-DEG_GlutamatergicNeuron1_brainRegions.qmd
          - text: Glutamatergic Neuron 2
            href: deg_analyses/20260310-DEG_GlutamatergicNeuron2_brainRegions.qmd
          - text: Glutamatergic Neuron 3
            href: deg_analyses/20260310-DEG_GlutamatergicNeuron3_brainRegions.qmd
          - text: Glutamatergic Neuron 4
            href: deg_analyses/20260310-DEG_GlutamatergicNeuron4_brainRegions.qmd
          - text: Glutamatergic Neuron 5
            href: deg_analyses/20260310-DEG_GlutamatergicNeuron5_brainRegions.qmd
          - text: Pericyte
            href: deg_analyses/20260310-DEG_Pericyte_brainRegions.qmd
          - text: Fibroblast
            href: deg_analyses/20260310-DEG_Fibroblast_brainRegions.qmd
          - text: VSMC
            href: deg_analyses/20260310-DEG_VSMC_brainRegions.qmd
          - text: VLMC
            href: deg_analyses/20260310-DEG_VLMC_brainRegions.qmd
          - text: Ependymal
            href: deg_analyses/20260310-DEG_Ependymal_brainRegions.qmd
          - text: CP
            href: deg_analyses/20260310-DEG_CP_brainRegions.qmd
      - text: Microglia
        menu:
          - text: Cell-type Proportions
            href: 20260303-cellType_proportions_microglia.qmd
          - text: GSEA-Immune Signatures
            href: 20260223-MG_GSEA_brainRegions.qmd
      - text: Astrocytes
        menu:
          - text: Reclustered from full object
            href: 20260305-astrocytes_reclustered.qmd
          - text: Cluster characterization
            href: 20260305-astrocytes_cluster_characterization.qmd
          - ---
          - text: Cleaned and reclustered again
            href: 20260309-astrocytes_reclustered_cleaned.qmd
          - text: Cell-type Proportions
            href: 20260310-cellType_proportions_astrocytes.qmd


format:
  html:
    theme: cosmo
    code-fold: true
    number-sections: false
    toc: true

knitr:
  opts_chunk:
    dev: svglite

execute:
  message: false
  warning: false
