project:
  type: website
  output-dir: docs

website:
  title: "ARIA Xenium Analysis"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Cell Types
        href: 20260302-cell_types.qmd
      - text: DE Analysis
        menu:
          - text: All cell types
            href: 20260304-DEG_allCellTypes_brainRegions.qmd
          - text: Microglia
            href: 20260303-DEG_MG_brainRegions.qmd
          - text: Astrocytes
            href: 20260303-DEG_astrocytes_brainRegions.qmd
          - text: Endothelial
            href: 20260303-DEG_ENDOTHELIAL_brainRegions.qmd
          - text: Oligodendrocytes
            href: 20260303-DEG_oligo_brainRegions.qmd
          - text: OPC
            href: 20260303-DEG_OPC_brainRegions.qmd
      - text: Microglia
        menu:
          - text: Proportions
            href: 20260303-cellType_proportions_microglia.qmd
      - text: GSEA
        href: 20260223-MG_GSEA_brainRegions.qmd
      - text: Astrocytes
        menu:
          - text: Reclustered
            href: 20260305-astrocytes_reclustered.qmd


format:
  html:
    theme: cosmo
    code-fold: true
    number-sections: false
    toc: true

knitr:
  opts_chunk:
    dev: svglite

execute:
  message: false
  warning: false
